from setuptools import setup, find_packages

setup(
    name='ai-citation-sdk',
    version='1.0.3',
    description='AIACTA Citation Webhook SDK for Python — signature verification, idempotency, and retry handling (Proposal 2, §3.4)',
    long_description=open('../../README.md', encoding='utf-8').read() if __import__('os').path.exists('../../README.md') else '',
    long_description_content_type='text/markdown',
    author='Eric Michel',
    author_email='contact@aiacta.org',
    url='https://github.com/aiacta-org/aiacta/tree/main/packages/ai-citation-sdk',
    project_urls={
        'Bug Tracker': 'https://github.com/aiacta-org/aiacta/issues',
        'Source': 'https://github.com/aiacta-org/aiacta',
        'Documentation': 'https://github.com/aiacta-org/aiacta/tree/main/packages/ai-citation-sdk#readme',
    },
    license='Apache-2.0',
    packages=find_packages(),
    python_requires='>=3.9',
    install_requires=[
        'cryptography>=41.0',
        'requests>=2.31',
    ],
    keywords=[
        'ai',
        'aiacta',
        'ai-attribution',
        'citation',
        'tracking',
        'monitoring',
        'webhook',
        'sdk',
        'hmac',
        'signature-verification',
        'content-attribution',
        'publisher-rights',
        'open-standard',
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
